### ISSUE TITLE
Duplicate Nodes

### ISSUE THREAD

**Issue by nestee74** [Stephan-S/FS25_AutoDrive#39]
This hopefully won't happen often but if a map has traffic splines and the map maker puts the same splines under AI splines, this causes autodrive to double up. Meaning when you start a new game save and AD wants to create a course for you, it then will place splines duplicated on top of each other. I have seen at least 2 maps that have come out that have this issue. I understand that this is not the way the map maker should be creating splines, as the AI will use the traffic spline without having to be in the AI spline transform group. I was just providing info for you in case there is a check that can be wriiten in for duplicates.

**Comment by ThomasMatern** [comment]
@nestee74 in general, I don't think this is a problem AutoDrive needs to solve - but rather the map maker.

However, I'm happy to have a look to check if there is an easy fix available. Can you send me a link to one of these problematic maps, please?

**Comment by nestee74** [comment]
https://www.dropbox.com/scl/fi/of9zl1anwxuq0uccjg8ht/FS25_Juotca_Map.zip?rlkey=017usjzf4rt7owbhnzsuc4e1n&st=n9fn55es&dl=0

**Comment by nestee74** [comment]
i agree with 100% that it is a map maker issue. The problem arises when you try to use AD it hangs and sometimes works, but has a long delay before the vehicle starts to move. Sometimes AD says can't get to destination. It took me awhile to figure out there was duplicate nodes on top of each other. I just didnt want users to think badly of AD and chalk it up as a bad mod. I sent you a dropbox link as the maker has changed the splines to be next to each other instead of on top of each other. Which still causes an issue. Here is the link to the updated map. https://farmingsimulator25mods.com/juotca-map-4x-v1-1/

**Comment by ThomasMatern** [comment]
Ok, so this is what we are looking at:
![image](https://github.com/user-attachments/assets/c10808d1-2a17-41ae-8863-5ea39d42a829)

The map contains two full sets of traffic splines, which are shifted slightly. This also confuses the built-in AI driver - it follows the left spline in this picture and will eventually run into a tree. This means that addressing this in AD is the wrong place - since AD can't fix the splines for the built-in AI driver. 
I'm closing this ticket - this issue needs to be fixed by the map maker.
